#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""汇总人工标注的回答准确率（正确/错误）。

输入：
- questions: `qa_system/eval_questions.jsonl`
- labels: `qa_system/outputs/labels_answer_correctness.jsonl`

输出：
- CSV: overall / by type
- LaTeX: `qa_system/outputs/answer_accuracy_tables.tex`

标签格式：
{"qid":"E001","mode":"fusion","is_correct":1,"notes":"..."}

说明：
- 该脚本只做汇总，不参与标注过程。
"""

from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Tuple


def load_jsonl(path: Path) -> Iterable[dict]:
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("//"):
                continue
            yield json.loads(line)


@dataclass
class Q:
    qid: str
    qtype: str


def load_questions(path: Path) -> Dict[str, Q]:
    out: Dict[str, Q] = {}
    for obj in load_jsonl(path):
        qid = str(obj.get("qid"))
        out[qid] = Q(qid=qid, qtype=str(obj.get("type")))
    return out


def load_labels(path: Path) -> List[dict]:
    return list(load_jsonl(path))


def mean(xs: List[int]) -> float:
    return sum(xs) / len(xs) if xs else 0.0


def write_csv(path: Path, rows: List[dict], fieldnames: List[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(rows)


def to_latex_table_overall(rows: List[dict]) -> str:
    # plain tabular: avoid siunitx dependency
    lines = []
    lines.append("% Auto-generated by qa_system/summarize_answer_accuracy.py")
    lines.append("% Recommended packages: \\\n% \\usepackage{booktabs}")
    lines.append("\\begin{table}[t]")
    lines.append("  \\centering")
    lines.append("  \\caption{不同检索策略的回答准确率对比（人工标注正确/错误，$n=30$）。}")
    lines.append("  \\label{tab:qa_answer_accuracy}")
    lines.append("  \\begin{tabular}{l r r}")
    lines.append("    \\toprule")
    lines.append("    方法 & $n$ & Accuracy \\\\")
    lines.append("    \\midrule")
    for r in rows:
        lines.append(f"    {r['method']} & {r['n']} & {r['accuracy']:.3f} \\\\")
    lines.append("    \\bottomrule")
    lines.append("  \\end{tabular}")
    lines.append("\\end{table}")
    return "\n".join(lines)


def to_latex_table_by_type(rows: List[dict]) -> str:
    lines = []
    lines.append("\\begin{table}[t]")
    lines.append("  \\centering")
    lines.append("  \\caption{按问题类型划分的回答准确率（人工标注正确/错误，每类$n=10$）。}")
    lines.append("  \\label{tab:qa_answer_accuracy_by_type}")
    lines.append("  \\begin{tabular}{l l r r}")
    lines.append("    \\toprule")
    lines.append("    方法 & 类型 & $n$ & Accuracy \\\\")
    lines.append("    \\midrule")
    for r in rows:
        lines.append(f"    {r['method']} & {r['type']} & {r['n']} & {r['accuracy']:.3f} \\\\")
    lines.append("    \\bottomrule")
    lines.append("  \\end{tabular}")
    lines.append("\\end{table}")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Summarize manual answer correctness labels")
    ap.add_argument("--questions", required=True, help="qa_system/eval_questions.jsonl")
    ap.add_argument("--labels", required=True, help="labels_answer_correctness.jsonl")
    ap.add_argument("--out_dir", default="qa_system/outputs", help="output dir")
    args = ap.parse_args()

    questions = load_questions(Path(args.questions))
    labels = load_labels(Path(args.labels))

    # group: method -> list[int]
    by_method: Dict[str, List[int]] = defaultdict(list)
    by_method_type: Dict[Tuple[str, str], List[int]] = defaultdict(list)

    missing_qids = 0
    for lab in labels:
        qid = str(lab.get("qid"))
        mode = str(lab.get("mode"))
        is_correct = int(lab.get("is_correct", 0))

        q = questions.get(qid)
        if not q:
            missing_qids += 1
            continue

        by_method[mode].append(is_correct)
        by_method_type[(mode, q.qtype)].append(is_correct)

    overall_rows = []
    for method in sorted(by_method.keys()):
        xs = by_method[method]
        overall_rows.append({"method": method, "n": len(xs), "accuracy": mean(xs)})

    by_type_rows = []
    for (method, qtype) in sorted(by_method_type.keys()):
        xs = by_method_type[(method, qtype)]
        by_type_rows.append({"method": method, "type": qtype, "n": len(xs), "accuracy": mean(xs)})

    out_dir = Path(args.out_dir)
    out_csv_overall = out_dir / "answer_accuracy_overall.csv"
    out_csv_by_type = out_dir / "answer_accuracy_by_type.csv"
    write_csv(out_csv_overall, overall_rows, ["method", "n", "accuracy"])
    write_csv(out_csv_by_type, by_type_rows, ["method", "type", "n", "accuracy"])

    out_tex = out_dir / "answer_accuracy_tables.tex"
    tex = to_latex_table_overall(overall_rows) + "\n\n" + to_latex_table_by_type(by_type_rows)
    out_tex.write_text(tex + "\n", encoding="utf-8")

    if missing_qids:
        print(f"[warn] labels contain {missing_qids} qid(s) not found in questions")

    print(f"[ok] wrote: {out_csv_overall}")
    print(f"[ok] wrote: {out_csv_by_type}")
    print(f"[ok] wrote: {out_tex}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
